services:
  ids:
    build: .
    container_name: ids_seguridad
    restart: unless-stopped

    env_file:
      - path: .env
        required: false

    environment:
      PORT: 5000
      SCAPY_ENABLE: ${SCAPY_ENABLE:-0}
      SCAPY_IFACE: ${SCAPY_IFACE:-}
      SCAPY_BPF: ${SCAPY_BPF:-}

    ports:
      - "5000:5000"

    cap_add:
      - NET_ADMIN
      - NET_RAW

    volumes:
      - .:/app

    working_dir: /app
